name: Build pdf for master
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
        with:
          ref: "master"
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: build

      - name: Copy compiled pdf
        run: |
          mkdir page_file
          cp ./main.pdf ./page_file/main.pdf
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: page_file
  deploy:
    needs: build_latex

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
